# Based on wxPython
# Copyright: (c) 2018 by Total Control Software
# License:   wxWindows License


def dummy_function(*args, **kwargs):
	return 0


EditStartupScriptDialog = object
Frame = object
ID_ABOUT = ''
ID_AUTOCOMP_DOUBLE = ''
ID_AUTOCOMP_MAGIC = ''
ID_AUTOCOMP_SHOW = ''
ID_AUTOCOMP_SINGLE = ''
ID_AUTO_SAVESETTINGS = ''
ID_CALLTIPS_INSERT = ''
ID_CALLTIPS_SHOW = ''
ID_CLEAR = ''
ID_CLEARHISTORY = ''
ID_CLOSE = ''
ID_COPY = ''
ID_COPY_PLUS = ''
ID_CUT = ''
ID_DELSETTINGSFILE = ''
ID_EDITSTARTUPSCRIPT = ''
ID_EMPTYBUFFER = ''
ID_ENABLEAUTOSYMPY = ''
ID_ENABLESHELLMODE = ''
ID_EXECSTARTUPSCRIPT = ''
ID_EXIT = ''
ID_FIND = ''
ID_FINDNEXT = ''
ID_FINDPREVIOUS = ''
ID_HELP = ''
ID_HIDEFOLDINGMARGIN = ''
ID_NAMESPACE = ''
ID_NEW = ''
ID_OPEN = ''
ID_PASTE = ''
ID_PASTE_PLUS = ''
ID_PRINT = ''
ID_REDO = ''
ID_REVERT = ''
ID_SAVE = ''
ID_SAVEACOPY = ''
ID_SAVEAS = ''
ID_SAVEHISTORY = ''
ID_SAVEHISTORYNOW = ''
ID_SAVESETTINGS = ''
ID_SELECTALL = ''
ID_SHOWPYSLICESTUTORIAL = ''
ID_SHOWTOOLS = ''
ID_SHOW_LINENUMBERS = ''
ID_TOGGLE_MAXIMIZE = ''
ID_UNDO = ''
ID_WRAP = ''
ShellFrameMixin = object
VERSION = ''
