# Based on wxPython
# Copyright: (c) 2018 by Total Control Software
# License:   wxWindows License


def dummy_function(*args, **kwargs):
	return 0


EVT_WEBVIEW_ERROR = ''
EVT_WEBVIEW_LOADED = ''
EVT_WEBVIEW_NAVIGATED = ''
EVT_WEBVIEW_NAVIGATING = ''
EVT_WEBVIEW_NEWWINDOW = ''
EVT_WEBVIEW_TITLE_CHANGED = ''
USE_WEBVIEW = 0
WEBVIEW_FIND_BACKWARDS = ''
WEBVIEW_FIND_DEFAULT = ''
WEBVIEW_FIND_ENTIRE_WORD = ''
WEBVIEW_FIND_HIGHLIGHT_RESULT = ''
WEBVIEW_FIND_MATCH_CASE = ''
WEBVIEW_FIND_WRAP = ''
WEBVIEW_NAV_ERR_AUTH = ''
WEBVIEW_NAV_ERR_CERTIFICATE = ''
WEBVIEW_NAV_ERR_CONNECTION = ''
WEBVIEW_NAV_ERR_NOT_FOUND = ''
WEBVIEW_NAV_ERR_OTHER = ''
WEBVIEW_NAV_ERR_REQUEST = ''
WEBVIEW_NAV_ERR_SECURITY = ''
WEBVIEW_NAV_ERR_USER_CANCELLED = ''
WEBVIEW_RELOAD_DEFAULT = ''
WEBVIEW_RELOAD_NO_CACHE = ''
WEBVIEW_ZOOM_LARGE = ''
WEBVIEW_ZOOM_LARGEST = ''
WEBVIEW_ZOOM_MEDIUM = ''
WEBVIEW_ZOOM_SMALL = ''
WEBVIEW_ZOOM_TINY = ''
WEBVIEW_ZOOM_TYPE_LAYOUT = ''
WEBVIEW_ZOOM_TYPE_TEXT = ''
WebView = object
WebViewArchiveHandler = object
WebViewBackendDefault = bytes()
WebViewBackendIE = bytes()
WebViewBackendWebKit = bytes()
WebViewDefaultURLStr = bytes()
WebViewEvent = object
WebViewFSHandler = object
WebViewFactory = object
WebViewFindFlags = object
WebViewHandler = object
WebViewHistoryItem = object
WebViewNameStr = bytes()
WebViewNavigationError = object
WebViewReloadFlags = object
WebViewZoom = object
WebViewZoomType = object
wxEVT_COMMAND_WEBVIEW_ERROR = 0
wxEVT_COMMAND_WEBVIEW_LOADED = 0
wxEVT_COMMAND_WEBVIEW_NAVIGATED = 0
wxEVT_COMMAND_WEBVIEW_NAVIGATING = 0
wxEVT_COMMAND_WEBVIEW_NEWWINDOW = 0
wxEVT_COMMAND_WEBVIEW_TITLE_CHANGED = 0
wxEVT_WEBVIEW_ERROR = 0
wxEVT_WEBVIEW_LOADED = 0
wxEVT_WEBVIEW_NAVIGATED = 0
wxEVT_WEBVIEW_NAVIGATING = 0
wxEVT_WEBVIEW_NEWWINDOW = 0
wxEVT_WEBVIEW_TITLE_CHANGED = 0
