# Based on wxPython
# Copyright: (c) 2018 by Total Control Software
# License:   wxWindows License


def dummy_function(*args, **kwargs):
	return 0


EVT_MEDIA_FINISHED = ''
EVT_MEDIA_LOADED = ''
EVT_MEDIA_PAUSE = ''
EVT_MEDIA_PLAY = ''
EVT_MEDIA_STATECHANGED = ''
EVT_MEDIA_STOP = ''
MEDIABACKEND_DIRECTSHOW = ''
MEDIABACKEND_GSTREAMER = ''
MEDIABACKEND_MCI = ''
MEDIABACKEND_QUICKTIME = ''
MEDIABACKEND_REALPLAYER = ''
MEDIABACKEND_WMP10 = ''
MEDIACTRLPLAYERCONTROLS_DEFAULT = ''
MEDIACTRLPLAYERCONTROLS_NONE = ''
MEDIACTRLPLAYERCONTROLS_STEP = ''
MEDIACTRLPLAYERCONTROLS_VOLUME = ''
MEDIASTATE_PAUSED = ''
MEDIASTATE_PLAYING = ''
MEDIASTATE_STOPPED = ''
MediaCtrl = object
MediaCtrlPlayerControls = object
MediaEvent = object
MediaState = object
USE_MEDIACTRL = 0
wxEVT_MEDIA_FINISHED = 0
wxEVT_MEDIA_LOADED = 0
wxEVT_MEDIA_PAUSE = 0
wxEVT_MEDIA_PLAY = 0
wxEVT_MEDIA_STATECHANGED = 0
wxEVT_MEDIA_STOP = 0
